# Generated by Django 5.2 on 2025-06-17 18:37

import laundry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('rng_code', models.CharField(default=laundry.models.generate_rng_code, max_length=10, unique=True)),
                ('service_type', models.CharField(choices=[('wash_fold', 'Wash & Fold'), ('express', 'Express Service'), ('dry_clean', 'Dry Cleaning')], max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_required', models.BooleanField(default=False)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_required', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('completion_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
